# Generated by Django 4.2.7 on 2023-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='no_image.png', upload_to='project', verbose_name='Изображение проекта'),
        ),
    ]
