# Generated by Django 4.2.7 on 2023-12-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img1',
            field=models.ImageField(default='no_image.png', upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='img2',
            field=models.ImageField(default='no_image.png', upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='img3',
            field=models.ImageField(default='no_image.png', upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='img4',
            field=models.ImageField(default='no_image.png', upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.TextField(default=1, verbose_name='Описание проекта'),
            preserve_default=False,
        ),
    ]
