# Generated by Django 4.2.7 on 2023-12-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_project_img1_project_img2_project_img3_project_img4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='no_image.png', unique=True, upload_to='project', verbose_name='Изображение для заголовка проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img1',
            field=models.ImageField(default='no_image.png', unique=True, upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img2',
            field=models.ImageField(default='no_image.png', unique=True, upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img3',
            field=models.ImageField(default='no_image.png', unique=True, upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img4',
            field=models.ImageField(default='no_image.png', unique=True, upload_to='project', verbose_name='Изображение проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(max_length=200, verbose_name='Роль в проекте'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название проекта'),
        ),
    ]
